/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const SettingLazyImport = createFileRoute('/setting')()
const ResultLazyImport = createFileRoute('/result')()
const CalculateLazyImport = createFileRoute('/calculate')()
const IndexLazyImport = createFileRoute('/')()

// Create/Update Routes

const SettingLazyRoute = SettingLazyImport.update({
  path: '/setting',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/setting.lazy').then((d) => d.Route))

const ResultLazyRoute = ResultLazyImport.update({
  path: '/result',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/result.lazy').then((d) => d.Route))

const CalculateLazyRoute = CalculateLazyImport.update({
  path: '/calculate',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/calculate.lazy').then((d) => d.Route))

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/calculate': {
      preLoaderRoute: typeof CalculateLazyImport
      parentRoute: typeof rootRoute
    }
    '/result': {
      preLoaderRoute: typeof ResultLazyImport
      parentRoute: typeof rootRoute
    }
    '/setting': {
      preLoaderRoute: typeof SettingLazyImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexLazyRoute,
  CalculateLazyRoute,
  ResultLazyRoute,
  SettingLazyRoute,
])

/* prettier-ignore-end */
